---

- name: "CentOS | check if ovirt-engine running (health page)"
  uri:
    url: "http://{{ovirt_engine_hostname}}/ovirt-engine/services/health"
    status_code: 200
  register: ovirt_engine_status
  retries: 2
  delay: 5
  until: ovirt_engine_status|success
  ignore_errors: True

- name: "CentOS | copy default answerfile"
  template:
    src: answerfile_{{ovirt_engine_version}}_basic.txt.j2
    dest: /tmp/answerfile.txt
    mode: 0644
    owner: root
    group: root

- name: "CentOS | run engine-setup with answerfile"
  shell: 'engine-setup --config-append=/tmp/answerfile.txt'
  when: ovirt_engine_status|failed

- name: "CentOS | check state of database"
  service:
    name: postgresql
    state: running
  when: ovirt_engine_db_host == 'localhost'

- name: "CentOS | check state of engine"
  service:
    name: ovirt-engine
    state: running

- name: "CentOS | restart of ovirt-engine service"
  service:
    name: ovirt-engine
    state: restarted

- name: "CentOS | check health status of page"
  uri:
    url: "http://{{ ovirt_engine_hostname }}/ovirt-engine/services/health"
    status_code: 200
  register: health_page
  retries: 12
  delay: 10
  until: health_page|success

- name: "CentOS | clean tmp files"
  file:
    path: '/tmp/answerfile.txt'
    state: 'absent'
