---

- name: "CentOS | Install Prerequisites"
  yum: 
   name: "{{ item }}"  
   state: present
  with_items:
    - centos-release-gluster

- name: "CentOS | Install Packages"
  yum: 
   name: "{{ item }}" 
   state: present
  with_items:
    - glusterfs-server
    - glusterfs-client

- name: "CentOS | Ensure GlusterFS is started and enabled at boot"
  service: 
   name: glusterd 
   state: started 
   enabled: yes
