---

- name: "CentOS | Ensure iptables is installed"
  package: name=iptables state=installed

- name: "CentOS | Flush iptables the first time playbook runs"
  command: >
    iptables -F
    creates=/etc/init.d/firewall

- name: "CentOS | Copy firewall script into place"
  template:
    src: firewall.bash.j2
    dest: /etc/firewall.bash
    owner: root
    group: root
    mode: 0744
  notify: restart firewall

- name: "CentOS | Copy firewall init script into place"
  template:
    src: firewall.init.j2
    dest: /etc/init.d/firewall
    owner: root
    group: root
    mode: 0755

- name: "CentOS | Copy firewall systemd unit file into place"
  template:
    src: firewall.unit.j2
    dest: /etc/systemd/system/firewall.service
    owner: root
    group: root
    mode: 0755

- name: "CentOS | Ensure the firewall is enabled and will start on boot"
  service: 
   name: firewall 
   state: started 
   enabled: yes
