---

- name: "CentOS | Install packages"
  yum: 
   name: "{{ item }}" 
   state: present
  with_items:
   - epel-release
   - qemu-kvm
   - git      
   - libvirt
   - virt-manager
   - bridge-utils
   - python-pip 
   - libvirt-python
   - libxml2-python
   - python-websockify
   - supervisor
   - nginx
   - net-tools

- name: "CentOS | enable and start libvirt"
  service: 
   name: libvirtd 
   state: restarted 
   enabled: yes

- name: "CentOS | setup port forwarding"
  sysctl: 
   name: "net.ipv4.ip_forward" 
   value: 1 
   sysctl_set: yes
